name: ai-agent-py
channels:
  - conda-forge
dependencies:
  - _openmp_mutex=4.5=4_kmp_llvm
  - _python_abi3_support=1.0=hd8ed1ab_2
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.12.15=py312h3d55d04_0
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - anyio=4.10.0=pyhe01879c_0
  - aom=3.9.1=hf036a51_0
  - attrs=25.3.0=pyh71513ae_0
  - aws-c-auth=0.8.1=h6661f4c_0
  - aws-c-cal=0.8.1=hc0df2db_3
  - aws-c-common=0.10.6=h6e16a3a_0
  - aws-c-compression=0.3.0=hc0df2db_5
  - aws-c-event-stream=0.5.0=h8236443_11
  - aws-c-http=0.9.2=h5492b4a_4
  - aws-c-io=0.15.3=h7bd4489_6
  - aws-c-mqtt=0.11.0=h3488609_12
  - aws-c-s3=0.7.9=h702e2dd_1
  - aws-c-sdkutils=0.2.2=hc0df2db_0
  - aws-checksums=0.2.2=hc0df2db_4
  - aws-crt-cpp=0.29.9=h5c43303_2
  - aws-sdk-cpp=1.11.489=h904bc55_0
  - brotli-python=1.1.0=py312h462f358_4
  - bzip2=1.0.8=hfdf4475_7
  - c-ares=1.34.5=hf13058a_0
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - certifi=2025.8.3=pyhd8ed1ab_0
  - cffi=1.17.1=py312hc05cdf7_1
  - charset-normalizer=3.4.3=pyhd8ed1ab_0
  - click=8.2.1=pyh707e725_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - cpython=3.12.11=py312hd8ed1ab_0
  - dataclasses=0.8=pyhc8e2a94_3
  - dav1d=1.2.1=h0dc2134_0
  - dill=0.3.7=pyhd8ed1ab_0
  - distro=1.9.0=pyhd8ed1ab_1
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - filelock=3.19.1=pyhd8ed1ab_0
  - frozenlist=1.7.0=py312h18bfd43_0
  - fsspec=2025.9.0=pyhd8ed1ab_0
  - gflags=2.2.2=hac325c4_1005
  - giflib=5.2.2=h10d778d_0
  - glog=0.7.1=h2790a97_0
  - gmp=6.3.0=hf036a51_2
  - gmpy2=2.2.1=py312he31a90d_1
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.3.0=pyhcf101f3_0
  - hf-xet=1.1.9=py310h75747b3_1
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - huggingface_hub=0.34.4=pyhd8ed1ab_1
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=h120a0e1_0
  - idna=3.10=pyhd8ed1ab_1
  - importlib-metadata=8.7.0=pyhe01879c_1
  - importlib_metadata=8.7.0=h40b2b14_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - jiter=0.10.0=py312h0d0de52_0
  - joblib=1.5.2=pyhd8ed1ab_0
  - kaldi=5.5.1112=cpu_h40adab0_7
  - krb5=1.21.3=h37d8d59_0
  - lcms2=2.17=h72f5680_0
  - lerc=4.0.0=hcca01a6_1
  - libabseil=20240722.0=cxx17_h0e468a2_4
  - libarrow=15.0.2=hc8bcee4_55_cpu
  - libarrow-acero=15.0.2=he6f7923_55_cpu
  - libarrow-dataset=15.0.2=he6f7923_55_cpu
  - libarrow-substrait=15.0.2=ha280db7_55_cpu
  - libavif16=1.3.0=h1c10324_2
  - libblas=3.9.0=20_osx64_mkl
  - libbrotlicommon=1.1.0=h1c43f85_4
  - libbrotlidec=1.1.0=h1c43f85_4
  - libbrotlienc=1.1.0=h1c43f85_4
  - libcblas=3.9.0=20_osx64_mkl
  - libcrc32c=1.1.2=he49afe7_0
  - libcurl=8.14.1=h5dec5d8_0
  - libcxx=21.1.0=h3d58e20_1
  - libde265=1.0.15=h7728843_0
  - libdeflate=1.24=hcc1b750_0
  - libedit=3.1.20250104=pl5321ha958ccf_0
  - libev=4.33=h10d778d_2
  - libevent=2.1.12=ha90c15b_1
  - libexpat=2.7.1=h21dd04a_0
  - libffi=3.4.6=h281671d_1
  - libfreetype=2.13.3=h694c41f_1
  - libfreetype6=2.13.3=h40dfd5c_1
  - libgfortran=15.1.0=h5f6db21_1
  - libgfortran5=15.1.0=hfa3c126_1
  - libgoogle-cloud=2.34.0=h7000a09_0
  - libgoogle-cloud-storage=2.34.0=h3f2b517_0
  - libgrpc=1.67.1=h4896ac0_2
  - libheif=1.19.7=gpl_h95ec88c_100
  - libhwloc=2.12.1=default_h094e1f9_1001
  - libiconv=1.18=h57a12c2_2
  - libjpeg-turbo=3.1.0=h6e16a3a_0
  - liblapack=3.9.0=20_osx64_mkl
  - liblapacke=3.9.0=20_osx64_mkl
  - liblzma=5.8.1=hd471939_2
  - libnghttp2=1.67.0=h3338091_0
  - libparquet=15.0.2=h89d5ab7_55_cpu
  - libpng=1.6.50=h84aeda2_1
  - libprotobuf=5.28.3=h6401091_1
  - libre2-11=2024.07.02=h0e468a2_2
  - libsqlite=3.50.4=h39a8b3b_0
  - libssh2=1.11.1=hed3591d_0
  - libthrift=0.21.0=h75589b3_0
  - libtiff=4.7.0=h59ddb5d_6
  - libtorch=2.6.0=cpu_mkl_h71ea9bc_101
  - libutf8proc=2.10.0=h5b79583_0
  - libuv=1.51.0=h58003a5_1
  - libwebp-base=1.6.0=hb807250_0
  - libxcb=1.17.0=hf1f96e2_0
  - libxml2=2.14.5=he78d85a_1
  - libxml2-16=2.14.5=h81c7dac_1
  - libzlib=1.3.1=hd23fc13_2
  - llvm-openmp=21.1.0=hf4e0ed4_0
  - lz4-c=1.10.0=h240833e_1
  - markupsafe=3.0.2=py312h3520af0_1
  - mkl=2023.2.0=h694c41f_50502
  - mpc=1.3.1=h9d8efa1_1
  - mpfr=4.2.1=haed47dc_3
  - mpmath=1.3.0=pyhd8ed1ab_1
  - multidict=6.6.3=py312h6f3313d_0
  - multiprocess=0.70.15=py312h104f124_1
  - ncurses=6.5=h0622a9a_3
  - networkx=3.5=pyhe01879c_0
  - numpy=2.3.2=py312hda18a35_2
  - openai=1.106.1=pyhd8ed1ab_0
  - openfst=1.8.3=h291f9dc_3
  - openjpeg=2.5.3=h036ada5_1
  - openssl=3.5.2=h6e31bce_0
  - optree=0.17.0=py312hedd4973_1
  - orc=2.0.3=h85ea3fe_2
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.2=py312hbf2c5ff_0
  - pillow=11.3.0=py312h528e901_1
  - pip=25.2=pyh8b19718_0
  - propcache=0.3.1=py312h3520af0_0
  - pthread-stubs=0.4=h00291cd_1002
  - pybind11=3.0.1=pyh7a1b43c_0
  - pybind11-global=3.0.1=pyhc7ab6ef_0
  - pycparser=2.22=pyh29332c3_1
  - pydantic=2.11.7=pyh3cfb1c2_0
  - pydantic-core=2.33.2=py312haba3716_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.12.11=h9ccd52b_0_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-gil=3.12.11=hd8ed1ab_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python-xxhash=3.5.0=py312h2e8b569_3
  - python_abi=3.12=8_cp312
  - pytorch=2.6.0=cpu_mkl_py312_h2c13ec0_101
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.2=py312h3520af0_2
  - rav1e=0.7.1=h371c88c_3
  - re2=2024.07.02=ha5e900a_2
  - readline=8.2=h7cca4af_2
  - regex=2025.7.34=py312h2f459f6_1
  - requests=2.32.5=pyhd8ed1ab_0
  - sacremoses=0.0.53=pyhd8ed1ab_0
  - safetensors=0.6.2=py312h864d763_1
  - scikit-learn=1.7.1=py312hf34d0c2_0
  - scipy=1.16.1=py312h67ab7b6_1
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - sleef=3.9.0=h289094c_0
  - snappy=1.2.2=h25c286d_0
  - sniffio=1.3.1=pyhd8ed1ab_1
  - svt-av1=3.1.2=h21dd04a_0
  - sympy=1.14.0=pyh2585a3b_105
  - tbb=2021.13.0=hc025b3e_3
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.13=hf689a15_2
  - tokenizers=0.22.0=py312h7ddc865_0
  - torchaudio=2.6.0=cpu_py312h98d886a_1
  - torchvision=0.21.0=cpu_py312_h6d70eb9_1
  - torchvision-extra-decoders=0.0.2=py312ha2042b6_2
  - tqdm=4.67.1=pyhd8ed1ab_1
  - transformers=4.17.0=pyhd8ed1ab_0
  - typing-extensions=4.15.0=h396c80c_0
  - typing-inspection=0.4.1=pyhd8ed1ab_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h78e105d_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - x265=3.5=hbb4e6a2_3
  - xorg-libxau=1.0.12=h6e16a3a_0
  - xorg-libxdmcp=1.1.5=h00291cd_0
  - xxhash=0.8.3=h13e91ac_0
  - yaml=0.2.5=h4132b18_3
  - yarl=1.20.1=py312h3520af0_0
  - zipp=3.23.0=pyhd8ed1ab_0
  - zstandard=0.24.0=py312hcfdedb4_1
  - zstd=1.5.7=h8210216_2
  - pip:
    - sqlite-vec==0.1.6

prefix: "/Users/core/miniforge3/envs/ai-agent-py"
